config/routes.rb
Rails.application.routes.draw do
  resources :links
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get ':short_url' => 'links#send_to_long_url'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord

  def gen_short_url
    # save the link first to get a record id
    self.save
    # convert the given id to a string base 36 to allow for very large numbers.
    self.short_url = self.id.to_s(36)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :destroy]

  # GET /links
  # GET /links.json
  def index
    @link = Link.new
  end


  def send_to_long_url
    @link = Link.find_by(short_url: params[:short_url].downcase)
    # make sure the link it in the db
    if @link
      # looks like it is so send user on his way
      redirect_to @link.main_url
    else
      # looks like there may be an issue
      respond_to do |format|
        format.html { redirect_to links_url, notice: 'Oops! looks like we could not find that link in our DB. Please check your info and try again.' }
        format.json { head :no_content }
      end
    end
  end

  # GET /links/new
  def new
    @link = Link.new
  end


  # POST /links
  # POST /links.json
  def create
    # quick way to gard against empty main url
    # full production version will need to check for a certain format.
    if params[:link][:main_url].empty?

      respond_to do |format|
        format.html { redirect_to links_url, notice: 'Looks like you forgot to give us a URL to link to.' }
        format.json { head :no_content }
      end
    else
      @link = Link.new(link_params)
      # lets go make that short url
      @link.gen_short_url
      respond_to do |format|
        if @link.save
          format.html { redirect_to links_url, notice: 'Congrats your new link is: localhost:3000/' + @link.short_url }
          format.json { render :show, status: :created, location: @link }
        else
          format.html { render :new }
          format.json { render json: @link.errors, status: :unprocessable_entity }
        end
      end
    end
  end


  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:main_url, :short_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shorturl</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
    <h3> Enter a link in the field below to generate a shortened link for sharing.</h3>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :main_url %>
    <%= form.text_field :main_url, id: :link_main_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<p id="notice"><%= notice %></p>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<div class="header"> <h1>Short Linker Code Challenge</h1> </div>

<div class="form_body">
<%= render 'form', link: @link %>
</div>

<br>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Main url:</strong>
  <%= @link.main_url %>
</p>

<p>
  <strong>Short url:</strong>
  <%= @link.short_url %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>